version: "3"

tasks:
  setup:
    cmds:
      - kind create cluster
      - kubectx kind-kind
      - linkerd install --crds | kubectl apply -f -
      - linkerd install | kubectl apply -f -
      - linkerd viz install | kubectl apply -f -
      - kubectl create namespace booksapp
      - kubectl annotate namespace booksapp "linkerd.io/inject=enabled"
      - kubens booksapp
      - curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/booksapp.yml | kubectl apply -f -

  reproduce:
    cmds:
      - kubectl apply -k .
      - kubectl apply -k linkerd
      - kubectl delete -k linkerd
      - kubectl apply -k gateway
      - kubectl delete -k gateway
